repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
        args: ["--fix", "--config", "pyproject.toml"]
      - id: ruff-format
        args: ["--config", "pyproject.toml"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
