name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Setup virtual environment
        run: uv venv
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install pre-commit bandit coverage
      - name: Run pre-commit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Run tests
        run: uv run coverage run -m pytest -q
      - name: Run bandit
        run: uv run bandit -r nonmouse -s B101 -x tests
